# Site settings
title: "Read Between the Beats"
description: "Harvee: Stress Monitor & Recovery Companion"
url: "https://harvee.app"
baseurl: ""

# Analytics / Search Console
google_analytics: "G-7VD9JRQVGR"
google_site_verification: "prtEYsT9vqrzuqVht0Dop6DX382az0CO8GHqONa3iU8"

# Author information
author:
  name: "Artie"
  email: "artie@harvee.app"
  twitter: "@harveeapp"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
timezone: "America/New_York"

# Blog settings
blog:
  title: "Harvee"
  description: "Insights on stress, recovery, and health optimization"
  paginate: 5
  paginate_path: "/blog/page:num"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Harvee Team"
      show_reading_time: true
  - scope:
      path: "blog"
      type: "pages"
    values:
      layout: "blog"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - _site/
  - .bundle/
  - run-jekyll.sh
